# 1. Dockerize data-processing
# 2. Push image to DockerHub
version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build:
          context: MIND-Data-Processing
jobs:
  build:
    environment:
      IMAGE_NAME: eelsherif/mind-app-getpath
    docker:
      - image: circleci/python:3.6.8  # primary container for the build job
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install --user --upgrade pip && pip --no-cache-dir install -r ./data_processing/getPathologyAnnotations/requirements.txt
      - run: cp ./config.yaml.template ./config.yaml
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest